spring.application.name=incident-api
server.port=8080

spring.datasource.url=jdbc:mysql://mysql:3306/incident?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=root
spring.datasource.username=incident
spring.datasource.password=incident
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.root=INFO
logging.level.com.shaun.incident_api=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.com.yourpackage=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

prometheus.base-url=http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090