apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: incident
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: shaun/frontend:v1.0.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
