apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: incident-ingress
  namespace: incident
spec:
  ingressClassName: traefik
  rules:
    - host: incident.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80